name: Test

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Conda environment
      uses: ./
      with:
        args: conda env update -f ./test/requirements.yml
    - name: Show Conda environment info
      uses: ./
      with:
        args: conda info
    - name: Prove that flake8 is installed
      uses: ./
      with:
        args: flake8 .
    - name: Prove that Pytest is installed
      uses: ./
      with:
        args: pytest ./test
