name: Test and Deploy

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Conda environment
      uses: ./
      with:
        args: conda env update -n base -f ./test/requirements.yml
    - name: Show Conda environment info
      uses: ./
      with:
        args: conda info
    - name: Prove that flake8 is installed
      uses: ./
      with:
        args: flake8 --version

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      IMAGETAG: "docker.pkg.github.com/${{github.repository}}/build:latest"
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file 'Dockerfile' --tag "${IMAGETAG}"
    - name: Deploy to GPR
      run: |
        docker login -u "${GITHUB_REPOSITORY%%/*}" --password-stdin 'docker.pkg.github.com' <<<'${{secrets.GITHUB_TOKEN}}'
        docker push "${IMAGETAG}"
